@CerealAPI_HostAddress = https://localhost:7022

GET {{CerealAPI_HostAddress}}/
Accept: application/json

###

GET {{CerealAPI_HostAddress}}/api/product
Accept: application/json
###

@id=0
GET {{CerealAPI_HostAddress}}/api/product/{{id}}
Accept: application/json
###
